name: Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch content
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Build website
        run: mkdocs build --strict

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Uploade artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

      - name: Deploy GitHub Pages
        uses: actions/deploy-pages@v4